


### Security Requests



###
GET /api/v1/security/csrf-token
Host: localhost:9010
Accept: application/json



### Image Requests



###
GET /api/v1/images/by-id?imageId=b95c58ca-fc6d-497e-ac3b-a7516bb71774
Host: localhost:9010
Accept: application/json



### IdentityRequests



###
POST /api/v1/identities/create
Host: localhost:9010
Accept: application/json
Content-Type: application/json
Origin: http://localhost:9010
X-Csrf-Token: fd6b20d4-5e49-430a-b46a-c305108a49c4

{
    "authority": "USER",
    "username": "zagor",
    "password": "zagor",
    "email": "zagor@gmail.com",
    "enabled": true,
    "firstname": "Загорулько",
    "lastname": "Борис",
    "patronymic": "Юрьевич"
}

###
GET /api/v1/identities
Host: localhost:9010
Accept: application/json
Authorization: Basic burgasvv@gmail.com burgasvv

###
GET /api/v1/identities/by-id?identityId=37a4e0be-d873-4776-ad9c-000c57ff99af
Host: localhost:9010
Accept: application/json
Authorization: Basic burgasvv@gmail.com burgasvv

###
PUT /api/v1/identities/update
Host: localhost:9010
Accept: application/json
Content-Type: application/json
Origin: http://localhost:9010
X-Csrf-Token: fd6b20d4-5e49-430a-b46a-c305108a49c4
Authorization: Basic zagor@gmail.com zagor

{
    "id": "3046569c-7050-4ea6-90e8-119513702102",
    "username": "zagorulko"
}

###
DELETE /api/v1/identities/delete?identityId=3046569c-7050-4ea6-90e8-119513702102
Host: localhost:9010
Accept: application/json
Origin: http://localhost:9010
X-Csrf-Token: 66a89a19-df90-4fa1-8321-5bfd42587dea
Authorization: Basic zagor@gmail.com zagor

###
DELETE /api/v1/identities/remove-image?identityId=3046569c-7050-4ea6-90e8-119513702102
Host: localhost:9010
Accept: application/json
Origin: http://localhost:9010
X-Csrf-Token: 66a89a19-df90-4fa1-8321-5bfd42587dea
Authorization: Basic zagor@gmail.com zagor

###
PUT /api/v1/identities/change-password
Host: localhost:9010
Accept: application/json
Content-Type: application/json
Origin: http://localhost:9010
X-Csrf-Token: 66a89a19-df90-4fa1-8321-5bfd42587dea
Authorization: Basic burgasvv@gmail.com burgasvv

{
    "id": "37a4e0be-d873-4776-ad9c-000c57ff99af",
    "password": "burgasvv111"
}



### Note Requests



###
POST /api/v1/notes/create
Host: localhost:9010
Accept: application/json
Content-Type: application/json
Origin: http://localhost:9010
X-Csrf-Token: bae9bd54-1c73-49bd-980b-2a3475c92089
Authorization: Basic burgasvv@gmail.com burgasvv

{
    "title": "New Note",
    "content": "Content from New Note",
    "identityId": "37a4e0be-d873-4776-ad9c-000c57ff99af"
}

###
PUT /api/v1/notes/update
Host: localhost:9010
Accept: application/json
Content-Type: application/json
Origin: http://localhost:9010
X-Csrf-Token: bae9bd54-1c73-49bd-980b-2a3475c92089
Authorization: Basic burgasvv@gmail.com burgasvv

{
    "id": "05606076-dd33-4a6c-bd4c-ada7c18092ba",
    "title": "New Note Test"
}

###
GET /api/v1/notes
Host: localhost:9010
Accept: application/json
Authorization: Basic burgasvv@gmail.com burgasvv

###
GET /api/v1/notes/by-id?noteId=05606076-dd33-4a6c-bd4c-ada7c18092ba
Host: localhost:9010
Accept: application/json
Authorization: Basic burgasvv@gmail.com burgasvv

###
DELETE /api/v1/notes/remove-images?noteId=05606076-dd33-4a6c-bd4c-ada7c18092ba
Host: localhost:9010
Accept: application/json
Content-Type: application/json
Origin: http://localhost:9010
X-Csrf-Token: 01e7c6ac-791e-42db-8bd2-21b2d44cb7ec
Authorization: Basic burgasvv@gmail.com burgasvv

{
    "imageIds": [
        "fd4c62b7-14c9-47c7-8021-bd8431f48c60",
        "f7df08a9-d630-4e37-959a-472dd5835af8"
    ]
}