
server:
  port: 9020
spring:
  application:
    name: java-spring
  datasource:
    driver-class-name: org.postgresql.Driver
    url: 'jdbc:postgresql://localhost:5020/java_spring_db'
    username: postgres
    password: postgres
  jpa:
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        highlight_sql: true
  liquibase:
    driver-class-name: org.postgresql.Driver
    url: 'jdbc:postgresql://localhost:5020/java_spring_db'
    user: postgres
    password: postgres
  data:
    redis:
      host: localhost
      port: 6020
logging:
  level:
    org.springframework.transaction.interceptor: TRACE